// Generated by gencpp from file control/FollowPathResponse.msg
// DO NOT EDIT!


#ifndef CONTROL_MESSAGE_FOLLOWPATHRESPONSE_H
#define CONTROL_MESSAGE_FOLLOWPATHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control
{
template <class ContainerAllocator>
struct FollowPathResponse_
{
  typedef FollowPathResponse_<ContainerAllocator> Type;

  FollowPathResponse_()
    : finished(false)
    , error(false)  {
    }
  FollowPathResponse_(const ContainerAllocator& _alloc)
    : finished(false)
    , error(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finished_type;
  _finished_type finished;

   typedef uint8_t _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::control::FollowPathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control::FollowPathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FollowPathResponse_

typedef ::control::FollowPathResponse_<std::allocator<void> > FollowPathResponse;

typedef boost::shared_ptr< ::control::FollowPathResponse > FollowPathResponsePtr;
typedef boost::shared_ptr< ::control::FollowPathResponse const> FollowPathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control::FollowPathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control::FollowPathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::control::FollowPathResponse_<ContainerAllocator1> & lhs, const ::control::FollowPathResponse_<ContainerAllocator2> & rhs)
{
  return lhs.finished == rhs.finished &&
    lhs.error == rhs.error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::control::FollowPathResponse_<ContainerAllocator1> & lhs, const ::control::FollowPathResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::control::FollowPathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control::FollowPathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control::FollowPathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control::FollowPathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control::FollowPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control::FollowPathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control::FollowPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3332c8c10694b43b1e4d49a22f0f93f";
  }

  static const char* value(const ::control::FollowPathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3332c8c10694b43ULL;
  static const uint64_t static_value2 = 0xb1e4d49a22f0f93fULL;
};

template<class ContainerAllocator>
struct DataType< ::control::FollowPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control/FollowPathResponse";
  }

  static const char* value(const ::control::FollowPathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control::FollowPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool finished\n"
"bool error\n"
"\n"
;
  }

  static const char* value(const ::control::FollowPathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control::FollowPathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finished);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowPathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control::FollowPathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control::FollowPathResponse_<ContainerAllocator>& v)
  {
    s << indent << "finished: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finished);
    s << indent << "error: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_MESSAGE_FOLLOWPATHRESPONSE_H
